import SchemDraw as schem
import SchemDraw.elements as e

d = schem.Drawing(lw=1)

# Transmon coupled to resonator
circuit = 'transmon_c_resonator'
d.add(e.DOT)
d.add(e.LINE, l = 0.5, d='left')
d.add(e.JJ, l = 3, d='up')
d.add(e.LINE, l = 0.5, d='right')
d.add(e.DOT)
d.push()
d.add(e.LINE, l = 0.5, d='right')
d.add(e.CAP, l = 3, d='down')
d.add(e.LINE, l = 0.5, d='left')
d.pop()
d.add(e.LINE, l = 0.5, d='up')
# d.add(e.LINE, l = 0.5, d='right')
d.add(e.CAP, l = 3, d='right')
# d.add(e.LINE, l = 0.5, d='right')
d.add(e.LINE, l = 0.5, d='down')
d.add(e.DOT)
d.add(e.LINE, l = 0.5, d='right')
d.add(e.CAP, l = 3, d='down')
d.add(e.LINE, l = 0.5, d='left')
d.add(e.DOT)
d.add(e.LINE, l = 0.5, d='left')
d.add(e.INDUCTOR, l = 3, d='up')
d.add(e.LINE, l = 0.5, d='right')

# LC
# circuit = 'lc'
# d.add(e.DOT)
# d.add(e.LINE, l = 0.5, d='up')
# d.add(e.INDUCTOR, l = 3, d='right')
# d.add(e.LINE, l = 0.5, d='down')
# d.add(e.DOT)
# d.add(e.LINE, l = 0.5, d='down')
# d.add(e.CAP, l = 3, d='left')
# d.add(e.LINE, l = 0.5, d='up')


# Transmon
# circuit = 'transmon'
# d.add(e.DOT)
# d.add(e.LINE, l = 0.5, d='up')
# d.add(e.JJ, l = 3, d='right')
# d.add(e.LINE, l = 0.5, d='down')
# d.add(e.DOT)
# d.add(e.LINE, l = 0.5, d='down')
# d.add(e.CAP, l = 3, d='left')
# d.add(e.LINE, l = 0.5, d='up')

# Fluxonium
# circuit = 'fluxonium'
# d.add(e.DOT)
# d.add(e.LINE, l = 1, d='up')
# d.add(e.INDUCTOR, l = 3, d='right')
# d.add(e.LINE, l = 1, d='down')
# d.add(e.DOT)
# d.push()
# d.add(e.JJ, l = 3, d='left')
# d.pop()
# d.add(e.LINE, l = 1, d='down')
# d.add(e.CAP, l = 3, d='left')
# d.add(e.LINE, l = 1, d='up')

# Flux Qubit
# circuit = 'fluxqubit'
# d.add(e.DOT)
# d.add(e.LINE, l = 0.5, d='right')
# d.push()
# d.add(e.JJ, l=2, d='right')
# d.pop()
# d.add(e.LINE, l = 0.5, d='up')
# d.add(e.CAP, l=2, d='right')
# d.add(e.LINE, l = 0.5, d='down')
# d.add(e.LINE, l = 0.5, d='right')
# d.add(e.DOT)
# d.add(e.LINE, l = 0.5, d='down')
# d.push()
# d.add(e.JJ, l=2, d='down')
# d.pop()
# d.add(e.LINE, l = 0.5, d='right')
# d.add(e.CAP, l = 2, d='down')
# d.add(e.LINE, l = 0.5, d='left')
# d.add(e.LINE, l = 0.5, d='down')
# d.add(e.LINE, l = 1.5, d='left')
# d.add(e.DOT)
# d.add(e.LINE, l = 1.5, d='left')
# d.add(e.LINE, l = 0.5, d='up')
# d.push()
# d.add(e.JJ, l = 2 , d='up')
# d.pop()
# d.add(e.LINE, l = 0.5, d='left')
# d.add(e.CAP, l = 2, d='up')
# d.add(e.LINE, l = 0.5, d='right')
# d.add(e.LINE, l = 0.5, d='up')

# d.add(e.DOT, label=r'$\Phi_{0}$', endpts=[[0,0],[0,0]])
# d.add(e.CAP, label=r'$C_1$', endpts=[[0,0],[3,5]], move_cur=False)
# Phi1 = d.add(e.DOT, label=r'$\Phi_{1}$', endpts=[[3,5],[3,5]], move_cur=False)
# d.add(e.LINE, l=1, d='right')
# d.add(e.LINE, l=1, d='up')
# d.add(e.CAP, l=3, d='right', label=r'$C_2$')
# d.add(e.LINE, l=1, d='down')
# d.push()
# d.add(e.LINE, l=1, d='down')
# d.add(e.JJ, l=3, d='left', label=r'$E_J$')
# d.add(e.LINE, l=1, d='up')
# d.pop()
# d.add(e.LINE, l=1, d='right')
# Phi2 = d.add(e.DOT, label=r'$\Phi_{2}$')
# d.add(e.INDUCTOR, label=r'$L_1$', endpts=[Phi2.start,Phi1.start])
# d.add(e.LINE, l=1, d='right')
# d.add(e.LINE, l=1, d='up')
# d.add(e.CAP, l=3, d='right', label=r'$C_3$')
# d.add(e.LINE, l=1, d='down')
# d.push()
# d.add(e.LINE, l=1, d='down')
# d.add(e.INDUCTOR, l=3, d='left', label=r'$L_2$')
# d.add(e.LINE, l=1, d='up')
# d.pop()
# d.add(e.LINE, l=1, d='right')
# Phi3 = d.add(e.DOT, label=r'$\Phi_{3}$')
# d.add(e.INDUCTOR, label=r'$L_3$', endpts=[Phi2.start,Phi3.start])
d.draw()
d.save(circuit+'_circuit.svg')
d.save(circuit+'_circuit.pdf')

